using System;
using System.Collections.Generic;

namespace MRD
{
    public static class OptionData
    {
        private static readonly Dictionary<string, Func<TowerOption>> towerOptionBuilders = new()
        {
            { nameof(ChanTaStatOption), () => new ChanTaStatOption() },
            { nameof(ChantaImageOption), () => new ChantaImageOption() },
            { nameof(CheongIlSaekStatOption), () => new CheongIlSaekStatOption() },
            { nameof(CheongIlSaekOption), () => new CheongIlSaekOption() },
            { nameof(CheongIlSaekImageOption), () => new CheongIlSaekImageOption() },
            { nameof(CheongNoDuStatOption), () => new CheongNoDuStatOption() },
            { nameof(CheongNoDuOption), () => new CheongNoDuOption() },
            { nameof(CheongNoDuImageOption), () => new CheongNoDuImageOption() },
            { nameof(ChiToiStatOption), () => new ChiToiStatOption() },
            { nameof(ChiToiOption), () => new ChiToiOption() },
            { nameof(ChiToiImageOption), () => new ChiToiImageOption() },
            { nameof(DaeChilSeongStatOption), () => new DaeChilSeongStatOption() },
            { nameof(DaeChilSeongOption), () => new DaeChilSeongOption() },
            { nameof(DaeChilSeongImageOption), () => new DaeChilSeongImageOption() },
            { nameof(DaeSaHeeStatOption), () => new DaeSaHeeStatOption() },
            { nameof(DaeSaHeeOption), () => new DaeSaHeeOption() },
            { nameof(DaeSaHeeImageOption), () => new DaeSaHeeImageOption() },
            { nameof(DaeSamWonStatOption), () => new DaeSamWonStatOption() },
            { nameof(DaeSamWonOption), () => new DaeSamWonOption() },
            { nameof(DaeSamWonImageOption), () => new DaeSamWonImageOption() },
            { nameof(DoraStatOption), () => new DoraStatOption() },
            { nameof(GukSaMuSangStatOption), () => new GukSaMuSangStatOption() },
            { nameof(GukSaMuSangOption), () => new GukSaMuSangOption() },
            { nameof(GukSaMuSangImageOption), () => new GukSaMuSangImageOption() },
            { nameof(GuRyeonBoDeungStatOption), () => new GuRyeonBoDeungStatOption() },
            { nameof(GuRyeonBoDeungOption), () => new GuRyeonBoDeungOption() },
            { nameof(GuRyeonBoDeungImageOption), () => new GuRyeonBoDeungImageOption() },
            { nameof(HonIlSaekStatOption), () => new HonIlSaekStatOption() },
            { nameof(HonIlSaekOption), () => new HonIlSaekOption() },
            { nameof(HonIlSaekImageOption), () => new HonIlSaekImageOption() },
            { nameof(HonNoDuStatOption), () => new HonNoDuStatOption() },
            { nameof(HonNoDuImageOption), () => new HonNoDuImageOption() },
            { nameof(IlGiTongGwanStatOption), () => new IlGiTongGwanStatOption() },
            { nameof(IlGiTongGwanOption), () => new IlGiTongGwanOption() },
            { nameof(IlGiTongGwanImageOption), () => new IlGiTongGwanImageOption() },
            { nameof(JailSaekStatOption), () => new JailSaekStatOption() },
            { nameof(JailSaekOption), () => new JailSaekOption() },
            { nameof(JailSaekImageOption), () => new JailSaekImageOption() },
            { nameof(JangPungPaeYeokPaeStatOption), () => new JangPungPaeYeokPaeStatOption() },
            { nameof(JangPungPaeYeokPaeOption), () => new JangPungPaeYeokPaeOption() },
            { nameof(JangPungPaeYeokPaeImageOption), () => new JangPungPaeYeokPaeImageOption() },
            { nameof(JunJJangStatOption), () => new JunJJangStatOption() },
            { nameof(JunJJangImageOption), () => new JunJJangImageOption() },
            { nameof(MadiTowerStatOption), () => new MadiTowerStatOption() },
            { nameof(MadiTowerOption), () => new MadiTowerOption() },
            { nameof(NokIlSaekStatOption), () => new NokIlSaekStatOption() },
            { nameof(NokIlSaekOption), () => new NokIlSaekOption() },
            { nameof(NokIlSaekImageOption), () => new NokIlSaekImageOption() },
            { nameof(PingHuStatOption), () => new PingHuStatOption() },
            { nameof(PingHuImageOption), () => new PingHuImageOption() },
            { nameof(RiChiStatOption), () => new RiChiStatOption() },
            { nameof(RiChiImageOption), () => new RiChiImageOption() },
            { nameof(RyangPeKoStatOption), () => new RyangPeKoStatOption() },
            { nameof(RyangPeKoOption), () => new RyangPeKoOption() },
            { nameof(RyangPeKoImageOption), () => new RyangPeKoImageOption() },
            { nameof(SamSaekDongGakStatOption), () => new SamSaekDongGakStatOption() },
            { nameof(SamSaekDongGakOption), () => new SamSaekDongGakOption() },
            { nameof(SamSaekDongGakImageOption), () => new SamSaekDongGakImageOption() },
            { nameof(SamSaekDongSoonStatOption), () => new SamSaekDongSoonStatOption() },
            { nameof(SamSaekDongSoonOption), () => new SamSaekDongSoonOption() },
            { nameof(SamSaekDongSoonImageOption), () => new SamSaekDongSoonImageOption() },
            { nameof(SamWonPaeYeokPaeStatOption), () => new SamWonPaeYeokPaeStatOption() },
            { nameof(SamWonPaeYeokPaeOption), () => new SamWonPaeYeokPaeOption() },
            { nameof(SamWonPaeYeokPaeImageOption), () => new SamWonPaeYeokPaeImageOption() },
            { nameof(SanAnKouStatOption), () => new SanAnKouStatOption() },
            { nameof(SanAnKouOption), () => new SanAnKouOption() },
            { nameof(SanAnKouImageOption), () => new SanAnKouImageOption() },
            { nameof(SanKantSuStatOption), () => new SanKantSuStatOption() },
            { nameof(SanKantSuOption), () => new SanKantSuOption() },
            { nameof(SanKantSuImageOption), () => new SanKantSuImageOption() },
            { nameof(ShuAnKouStatOption), () => new ShuAnKouStatOption() },
            { nameof(ShuAnKouOption), () => new ShuAnKouOption() },
            { nameof(ShuAnKouImageOption), () => new ShuAnKouImageOption() },
            { nameof(ShuKantSuStatOption), () => new ShuKantSuStatOption() },
            { nameof(ShuKantSuOption), () => new ShuKantSuOption() },
            { nameof(ShuKantSuImageOption), () => new ShuKantSuImageOption() },
            { nameof(SingleTowerStatOption), () => new SingleTowerStatOption() },
            { nameof(SoSaHeeStatOption), () => new SoSaHeeStatOption() },
            { nameof(SoSaHeeOption), () => new SoSaHeeOption() },
            { nameof(SoSaHeeImageOption), () => new SoSaHeeImageOption() },
            { nameof(SoSamWonStatOption), () => new SoSamWonStatOption() },
            { nameof(SoSamWonOption), () => new SoSamWonOption() },
            { nameof(SoSamWonImageOption), () => new SoSamWonImageOption() },
            { nameof(TangYaoStatOption), () => new TangYaoStatOption() },
            { nameof(TangYaoOption), () => new TangYaoOption() },
            { nameof(TangYaoImageOption), () => new TangYaoImageOption() },
            { nameof(ToiToiStatOption), () => new ToiToiStatOption() },
            { nameof(ToiToiOption), () => new ToiToiOption() },
            { nameof(ToiToiImageOption), () => new ToiToiImageOption() },
            { nameof(YiPeKoStatOption), () => new YiPeKoStatOption() },
            { nameof(YiPeKoOption), () => new YiPeKoOption() },
            { nameof(YiPeKoImageOption), () => new YiPeKoImageOption() },
        };

        public static TowerOption GetOption(string name) =>
            towerOptionBuilders.TryGetValue(name, out var v) ? v() : null;
    }
}
